### ISSUE TITLE
Make tests robust to non-AES ciphersuites

### ISSUE THREAD

**Issue by jdtw** [square/certigo#267]
I was a bit late to chime in with a review before this got merged.
One other source of test failures was the assumption of AES_128_GCM_SHA256 being selected by both the `httptest` spawned TLS server and the unit test TLS client.

Go alters the default ciphersuite to prefer ChaPoly over AES-GCM suites if the underlying hardware doesn't have AES extensions. (https://cs.opensource.google/go/go/+/master:src/crypto/tls/handshake_server_tls13.go;l=158?q=defaultCipherSuitesTLS13NoAES%20&ss=go%2Fgo). So CI/CD systems running under virtualization may not always reflect the underlying CPUs extensions. One good example—and how I ended up debugging this issue—was NixOS CI system for Darwin x86-64 wasn't picking AES. Temporarily I ended up [disabling tests on darwin-x86_64](https://github.com/NixOS/nixpkgs/commit/62595afea705348c4fe25bb8bf8996bc03a75ed0).

So the lines [110](https://github.com/square/certigo/blob/5332ac7ca20bdea63657cc8319e8b8fda4326938/cli/cli_test.go#L110) and [138](https://github.com/square/certigo/blob/5332ac7ca20bdea63657cc8319e8b8fda4326938/cli/cli_test.go#L110) for `expectedConnect` string in `TestConnect` trying to match `Cipher Suite: AES_128_GCM_SHA256 cipher` will continue causing test failures where Go cannot deduce presence of hardware acceleration for AES.

_Originally posted by @bdd in https://github.com/square/certigo/issues/265#issuecomment-1143986770_

**Comment by bdd** [comment]
>  Hardcoding TLS 1.3 is also fragile.

Certigo requires [at least Go 1.13](https://github.com/square/certigo/blob/master/go.mod#L24).
Go added TLS 1.3 support in 1.12 as opt-in and promoted it to on-by-default in [1.13](https://go.dev/doc/go1.13#tls_1_3).
Go [always chooses `MaxVersion`](https://cs.opensource.google/go/go/+/master:src/crypto/tls/common.go;drc=ec7f5165ddc680efbac18dc15b4905844d9e8db9;l=698). Due to the nature of the unit test, the server and the client are instantiated in the same process. So as long as there's no TLS 1.4 in Go, you're good. That's gonna take long years to land :)

**Comment by jdtw** [comment]
Yeah, I was imaging TLS 1.4 :). But yeah, those 20 year certs will probably expire before then, too...
